allow skipped tests
lamby/travis.debian.net pull request #39
Opened 2017-01-06 20:06 UTC by evgeni

autopkgtest will exit 2 when there were skipped tests, but that's OK, so let's catch that and not fail

2017-01-06 20:14 UTC, lamby commented
Love the idea but can you push again but following the style conventions (eg. tabs, upper-case variables, etc. etc. etc.)

2017-01-06 20:24 UTC, evgeni commented
done

2017-01-06 20:51 UTC, lamby requested changes
Thanks, but I think you missed a few things :)

2017-01-06 20:51 UTC, lamby commented on script.sh
> +	echo "${TRAVIS_DEBIAN_AUTOPKGTEST_RUN} exited ${TEST_RET}"
Perhaps print this to stderr?

2017-01-06 20:51 UTC, lamby commented on script.sh
> +${TRAVIS_DEBIAN_AUTOPKGTEST_RUN} ${TRAVIS_DEBIAN_BUILD_DIR}/*.changes ${TRAVIS_DEBIAN_AUTOPKGTEST_SEPARATOR} null || TEST_RET=$?
``=$?``  → ``="${?}"``

2017-01-06 20:51 UTC, lamby commented on script.sh
> +TEST_RET=0
``="0"``

2017-01-06 20:51 UTC, lamby commented on script.sh
> +if [ ${TEST_RET} -ne 0 ] && [ ${TEST_RET} -ne 2 ]; then
please quote these too and the ``then`` should be on a newline without a semicolon.

2017-01-09 23:41 UTC, evgeni commented
if gh would just have a button to mark all those requested changes als done...

2017-01-10 17:59 UTC, merged

2017-01-10 17:59 UTC, lamby commented
Many thanks!

2017-01-11 17:37 UTC, lamby commented
FYI this needed 634b579883519e9f06beeaba1273f8def91e7535 :)

2017-01-11 17:42 UTC, evgeni commented
Right. Sorry!

On January 11, 2017 6:37:22 PM GMT+01:00, Chris Lamb <notifications@github.com> wrote:
>FYI this needed 634b579883519e9f06beeaba1273f8def91e7535 :)

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

2017-01-11 17:47 UTC, lamby commented
@evgeni No problem at all, just thought I'd mention it as it's quite a "cute" error :)