Add TRAVIS_DEBIAN_COMPONENTS option
lamby/travis.debian.net pull request #55
Opened 2018-01-15 10:19 UTC by didrocks

2018-01-15 21:49 UTC, lamby requested changes

2018-01-15 21:49 UTC, lamby commented on index.html
> +        By default, this is set to "main".
Please wrap main in tt tag

2018-01-15 21:49 UTC, lamby commented on index.html
> +        Additional components used for building and testing this package.
"Additional archive components" might be useful here.

2018-01-16 07:31 UTC, didrocks commented
Thanks for the review! Both comments addressed

2018-01-16 08:26 UTC, didrocks commented
Was merged with PR #56, closing.

2018-01-16 08:26 UTC, closed without merging